[package]
name = "first_os"
version = "0.1.0"
edition = "2018"
author = "Miguelfarialopes2729"  

# the profile used for `cargo build`
[profile.dev]
panic = "abort" # disable stack unwinding on panic

# the profile used for `cargo build --release`
[profile.release]
panic = "abort" # disable stack unwinding on panic


[dependencies]
bootloader = "0.11.10" #while i dont make a native bootloader bootimage will have to do
volatile = "0.6.1" #reads invalid ASCII and turns it into readable code
spin = "0.9.8" #So we can use Spinlock to block threads already in use
x86_64 = "0.15.2"
uart_16550 = "0.3.2"
pc-keyboard = "0.8.0"


[dependencies.lazy_static] #To solve one-time initialization of statics with non-const functions being a problem
version = "1.0"
features = ["spin_no_std"]



[package.metadata.bootimage]
test-args = [
    "-device", "isa-debug-exit,iobase=0xf4,iosize=0x04", "-serial", "stdio",
    "-display", "none"
]
test-timeout = 180          # (in seconds)

[[test]]
name = "should_panic"
harness = false

[[test]]
name = "stack_overflow"
harness = false